name: application-ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    - uses: actions/checkout@v3

    - name: Copying .env
      run: echo "${{ secrets.ENV_FILE }}" > .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run tests with phpunit
      run: vendor/bin/phpunit
  release:
    runs-on: ubuntu-latest
    steps:
    # - name: registering ssh
    #   run: ssh-add < (echo "${{ secrets.SSH_PRIVATE_KEY }}")
    - uses: actions/checkout@v3

    - name: updating server commit
      run: ssh -i cicd@${{ secrets.PRODUCTION_IP }} -t 'cd /app/voter && echo "${{ secrets.ENV_FILE }}" > .env && git pull'


